// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/data.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiceClient is the client API for Dice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type diceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiceClient(cc grpc.ClientConnInterface) DiceClient {
	return &diceClient{cc}
}

func (c *diceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/proto.Dice/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiceServer is the server API for Dice service.
// All implementations must embed UnimplementedDiceServer
// for forward compatibility
type DiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedDiceServer()
}

// UnimplementedDiceServer must be embedded to have forward compatible implementations.
type UnimplementedDiceServer struct {
}

func (UnimplementedDiceServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedDiceServer) mustEmbedUnimplementedDiceServer() {}

// UnsafeDiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiceServer will
// result in compilation errors.
type UnsafeDiceServer interface {
	mustEmbedUnimplementedDiceServer()
}

func RegisterDiceServer(s grpc.ServiceRegistrar, srv DiceServer) {
	s.RegisterService(&Dice_ServiceDesc, srv)
}

func _Dice_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Dice/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dice_ServiceDesc is the grpc.ServiceDesc for Dice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Dice",
	HandlerType: (*DiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Dice_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/data.proto",
}
